"""
Email utility for sending PDF reports
"""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from django.conf import settings
import logging

logger = logging.getLogger(__name__)


def send_pdf_report_email(recipient_email, recipient_name, pdf_buffer, report_type, admin_name):
    """
    Send PDF report via email
    
    Args:
        recipient_email: Email address to send to
        recipient_name: Name of recipient
        pdf_buffer: BytesIO buffer containing PDF
        report_type: Type of report (users, predictions, waste)
        admin_name: Name of admin who generated the report
    
    Returns:
        tuple: (success: bool, message: str)
    """
    try:
        # Email configuration
        smtp_server = getattr(settings, 'EMAIL_HOST', 'smtp.gmail.com')
        smtp_port = getattr(settings, 'EMAIL_PORT', 587)
        sender_email = getattr(settings, 'EMAIL_HOST_USER', '')
        sender_password = getattr(settings, 'EMAIL_HOST_PASSWORD', '')
        
        if not sender_email or not sender_password:
            return False, "Email configuration not set. Please configure EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in settings."
        
        # Create message
        msg = MIMEMultipart()
        msg['From'] = f"AluOptimize <{sender_email}>"
        msg['To'] = recipient_email
        msg['Subject'] = f"AluOptimize {report_type.title()} Report"
        
        # Email body
        body = f"""
Dear {recipient_name},

Your {report_type} report has been generated by {admin_name}.

This report contains detailed information about your aluminum production optimization data.

Please find the PDF report attached to this email.

If you have any questions about this report, please contact your administrator.

Best regards,
AluOptimize Team

---
This is an automated email. Please do not reply to this message.
        """.strip()
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach PDF
        pdf_buffer.seek(0)
        attachment = MIMEBase('application', 'pdf')
        attachment.set_payload(pdf_buffer.read())
        encoders.encode_base64(attachment)
        
        filename = f"aluoptimize_{report_type}_report.pdf"
        attachment.add_header('Content-Disposition', f'attachment; filename={filename}')
        msg.attach(attachment)
        
        # Send email
        logger.info(f"Attempting to send email to {recipient_email} via {smtp_server}:{smtp_port}")
        
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        
        logger.info(f"Successfully sent {report_type} report to {recipient_email}")
        return True, f"Report successfully emailed to {recipient_email}"
        
    except smtplib.SMTPAuthenticationError as e:
        logger.error(f"SMTP authentication failed: {str(e)}")
        return False, "Email authentication failed. Please check email credentials."
    
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error: {str(e)}")
        return False, f"Failed to send email: {str(e)}"
    
    except Exception as e:
        logger.error(f"Error sending email: {str(e)}", exc_info=True)
        return False, f"Error sending email: {str(e)}"


def send_bulk_pdf_reports(recipients, pdf_buffer, report_type, admin_name):
    """
    Send PDF report to multiple recipients
    
    Args:
        recipients: List of dicts with 'email' and 'name' keys
        pdf_buffer: BytesIO buffer containing PDF
        report_type: Type of report
        admin_name: Name of admin who generated the report
    
    Returns:
        dict: Results with success/failure counts and messages
    """
    results = {
        'success_count': 0,
        'failure_count': 0,
        'messages': []
    }
    
    for recipient in recipients:
        email = recipient.get('email')
        name = recipient.get('name', 'User')
        
        if not email:
            results['failure_count'] += 1
            results['messages'].append(f"Skipped {name}: No email address")
            continue
        
        # Reset buffer position for each send
        pdf_buffer.seek(0)
        
        success, message = send_pdf_report_email(
            email, name, pdf_buffer, report_type, admin_name
        )
        
        if success:
            results['success_count'] += 1
        else:
            results['failure_count'] += 1
        
        results['messages'].append(f"{name} ({email}): {message}")
    
    return results
