# Generated by Django 5.2.7 on 2025-11-04 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediction', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_type', models.CharField(max_length=100)),
                ('waste_amount', models.FloatField()),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('TON', 'Tons'), ('L', 'Liters')], default='KG', max_length=10)),
                ('date_recorded', models.DateField()),
                ('reuse_possible', models.BooleanField(default=False)),
                ('production_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='prediction.productioninput')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Record',
                'verbose_name_plural': 'Waste Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_text', models.TextField()),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('waste_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='waste.wastemanagement')),
            ],
            options={
                'verbose_name': 'Waste Recommendation',
                'verbose_name_plural': 'Waste Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wastemanagement',
            index=models.Index(fields=['-date_recorded'], name='waste_waste_date_re_2a6548_idx'),
        ),
        migrations.AddIndex(
            model_name='wastemanagement',
            index=models.Index(fields=['waste_type'], name='waste_waste_waste_t_23278f_idx'),
        ),
    ]
