# Generated by Django 5.2.7 on 2025-11-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastemanagement',
            name='energy_used',
            field=models.FloatField(blank=True, help_text='Energy consumption in kWh', null=True),
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='pressure',
            field=models.FloatField(blank=True, help_text='Pressure in Pa', null=True),
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='production_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='wasterecommendation',
            name='ai_generated',
            field=models.BooleanField(default=True, help_text='Whether this recommendation was AI-generated'),
        ),
    ]
