# Generated by Django 5.2.7 on 2025-11-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wastemanagement_energy_used_wastemanagement_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastemanagement',
            name='sent_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wasterecommendation',
            name='sent_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
